repo: 'exploding-robot-head'
canvasCourse: 'web-dev-1'

inherit:
  - naming-restrict-live
  - git-2
  - css
  - box-sizing
  - body-margin-0

html:
  - path: 'index.html'
    locked: true

css:
  - path: 'css/main.css'
    search:
      - 'position: relative'
      - 'position: absolute'
      - 'left'
      - 'right'
      - 'top'

screenshots:
  - path: 'index.html'
    label: 'Before'
    sizes: [320, 980]
  - path: 'index.html'
    label: 'After'
    sizes: [980]
    before: |
      on('.robot-brain', 'transitionend', done)
      hover('.robot');

functionality:
  - path: index.html
    tests:
      - |
        var left = $('.robot-head-left');
        var oldLPos = left.getBoundingClientRect().top;
        var right = $('.robot-head-right');
        var oldRPos = right.getBoundingClientRect().top;
        var brain = $('.robot-brain');
        var oldBPos = brain.getBoundingClientRect().top;

        hover('.robot', function () {
          if (left.getBoundingClientRect().top === oldLPos) fail('The position of the robot’s left head piece doesn’t change when the robot is hovered');
          if (right.getBoundingClientRect().top === oldRPos) fail('The position of the robot’s right head piece doesn’t change when the robot is hovered');
          if (brain.getBoundingClientRect().top === oldBPos) fail('The position of the robot’s brain doesn’t change when the robot is hovered');
          pass();
        });
