repo: "exploding-robot-head"
canvasCourse: "web-dev-1"

naming: true
restrictFileTypes: true
liveWebsite: true

git:
  numCommits: 2
  allCommitted: true
  allSynced: true

html:
  - path: "index.html"
    locked: true

css:
  - path: "css/main.css"
    valid: true
    bestPractices: true
    has:
      - ['html', 'box-sizing', 'border-box']
      - ['*', 'box-sizing', 'inherit']
      - ['body', 'margin', 0]
    search:
      - "position: relative"
      - "position: absolute"
      - "left"
      - "right"
      - "top"

screenshots:
  - path: "index.html"
    sizes: [320, 980]

functionality:
  - path: index.html
    tests:
      - |
        var left = $('.robot-head-left');
        var oldLPos = left.getBoundingClientRect().top;
        var right = $('.robot-head-right');
        var oldRPos = right.getBoundingClientRect().top;
        var brain = $('.robot-brain');
        var oldBPos = brain.getBoundingClientRect().top;

        hover('.robot', function () {
          if (left.getBoundingClientRect().top === oldLPos) fail('The position of the robot’s left head piece doesn’t change when the robot is hovered');
          if (right.getBoundingClientRect().top === oldRPos) fail('The position of the robot’s right head piece doesn’t change when the robot is hovered');
          if (brain.getBoundingClientRect().top === oldBPos) fail('The position of the robot’s brain doesn’t change when the robot is hovered');
          pass();
        });
